name: 도커 이미지 빌드
on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:
jobs:
  api-build:
    name: "API 빌드"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.package-version.outputs.version }}_build_${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Add token in .npmrc
        env:
          NPM_TOKEN: ${{ secrets.GIT_TOKEN }} 
        run: |
          echo -e "\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}
  
      - name: LowerCase
        id: repository_lower
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Build Dockerfile
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/${{ steps.repository_lower.outputs.lowercase }}:latest
            ghcr.io/${{ steps.repository_lower.outputs.lowercase }}:${{ steps.package-version.outputs.version }}_build_${{ github.run_number }}
          build-args: |
            NPM_TOKEN=${{ secrets.GIT_TOKEN }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_TOKEN }}
  image-build:
    name: "Image서버 빌드"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.package-version.outputs.version }}_build_${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
            
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Add token in .npmrc
        env:
          NPM_TOKEN: ${{ secrets.GIT_TOKEN }} 
        run: |
          echo -e "\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: LowerCase
        id: repository_lower
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
  
      - name: Build Dockerfile
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          file: ./Dockerfile-image
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/${{ steps.repository_lower.outputs.lowercase }}-image:latest
            ghcr.io/${{ steps.repository_lower.outputs.lowercase }}-image:${{ steps.package-version.outputs.version }}_build_${{ github.run_number }}
          build-args: |
            NPM_TOKEN=${{ secrets.GIT_TOKEN }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_TOKEN }}